# Generated by Django 3.1.7 on 2021-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_auto_20210511_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/images'),
        ),
    ]
