# Generated by Django 3.1.7 on 2021-05-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tuition/images'),
        ),
    ]
