# Generated by Django 3.1.7 on 2021-05-12 20:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0011_auto_20210512_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Hindi', 'Hindi'), ('Spanis', 'Spanis')], default='Bangla', max_length=100),
        ),
    ]
